### PR TITLE
More type coverage

### PR DESCRIPTION
**Pull request by sloria**

### CODE REVIEW

**Comment by sloria** [comment]
this needs https://github.com/marshmallow-code/marshmallow/pull/2744.

Otherwise I get the following errors from mypy

```
marshmallow-sqlalchemy ❯ mypy .
src/marshmallow_sqlalchemy/schema.py:182: error: Definition of "opts" in base class "Schema" is incompatible with definition in base class "Schema"  [misc]
tests/test_sqlalchemy_schema.py:74: error: Definition of "opts" in base class "Schema" is incompatible with definition in base class "Schema"  [misc]
tests/test_sqlalchemy_schema.py:102: error: Definition of "opts" in base class "Schema" is incompatible with definition in base class "Schema"  [misc]
Found 3 errors in 2 files (checked 11 source files)
```

**Comment by sloria** [comment]
works in mypy with marshmallow 3.25.0
